name: Loan Data Pipeline

on:
  workflow_dispatch:

  schedule:
    - cron: "*/2 * * * *"

jobs:
  run-pipeline:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Data Pipeline
        run: |
          python src/run_pipeline.py